version: "3"
services:
  deploy-frontend:
    build:
      context: ./
      dockerfile: Dockerfile
    command:
      - "sleep"
      - "10"
    ports: 
    - "8082:8082"
    environment:
      PORT: ${PORT}
      GOOGLE_WELL_KNOWN_URL: ${GOOGLE_WELL_KNOWN_URL}
      GOOGLE_CLIENT_ID: ${GOOGLE_CLIENT_ID}
      GOOGLE_CLIENT_SECRET: ${GOOGLE_CLIENT_SECRET}
      GOOGLE_REDIRECT_URL: ${GOOGLE_REDIRECT_URL}
      GOOGLE_LOGOUT_REDIRECT_URL: ${GOOGLE_LOGOUT_REDIRECT_URL}
      COOKIE_KEY: ${COOKIE_KEY}
      DOWNSTREAM_API_PRE_SHARED_KEY: ${DOWNSTREAM_API_PRE_SHARED_KEY}
      DOWNSTREAM_API_URL: ${DOWNSTREAM_API_URL}
      AUTHENTICATION_ENABLED: ${AUTHENTICATION_ENABLED}
      AUTHENTICATION_PROVIDER: ${AUTHENTICATION_PROVIDER}
