apiVersion: "nais.io/v1alpha1"
kind: "Application"
metadata:
  name: deploy-frontend
  namespace: aura
  labels:
    team: aura
spec:
  accessPolicy:
    outbound:
      rules: 
        application: hookd-gcp
        application: hookd 
      external:
{{#each external-hosts}}
      - host: {{this}}
{{/each}}
      rules: []
  image: {{ image }}
  port: 8080 
  liveness:
    path: /isalive
  readiness:
    path: /isalive
  replicas:
    min: 1
    max: 1
  ingresses:
    {{#each ingresses}}
    - "{{this}}"
    {{/each}}
  envFrom: 
    - secret: deploy-frontend-secrets
  env:
{{#each envs}}
    - name: "{{name}}"
      value: "{{value}}"
{{/each}}
  skipCaBundle: true
  resources:
    limits:
      cpu: 500m 
      memory: 512Mi
    requests:
      cpu: 200m
      memory: 256Mi