name: Build and deploy nais-deploy-frontend
on: [push, pull_request]
jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@ac593985615ec2ede58e132d2e21d2b1cbd6127c # ratchet:actions/checkout@v3
      - name: Setup node
        uses: actions/setup-node@1f8c6b94b26d0feae1e387ca63ccbdc44d27b561 # ratchet:actions/setup-node@v2
        with:
          node-version: '16.x'
      - name: Get yarn cache directory path
        id: yarn-cache-dir-path
        run: echo "dir=$(yarn cache dir)" >> ${GITHUB_OUTPUT}
      - uses: actions/cache@69d9d449aced6a2ede0bc19182fadc3a0a42d2b0 # ratchet:actions/cache@v3
        id: yarn-cache # use this to check for `cache-hit` (`steps.yarn-cache.outputs.cache-hit != 'true'`)
        with:
          path: ${{ steps.yarn-cache-dir-path.outputs.dir }}
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-
      - name: Download dependencies
        run: yarn install --frozen-lockfile
      - name: Run tests
        run: yarn test

  build-push-sign:
    name: Build, push and sign image
    runs-on: ubuntu-latest
    permissions:
      contents: "read"
      id-token: "write"
    steps:
      - uses: actions/checkout@ac593985615ec2ede58e132d2e21d2b1cbd6127c # ratchet:actions/checkout@v3
      - uses: nais/build-push-sign@main
        id: build-push-sign
        with:
          name: deploy-frontend
          service_account: gh-deploy-frontend
    outputs:
      version: "${{ steps.build-push-sign.outputs.version }}"

  rollout:
    name: Rollout with Fasit
    if: github.ref == 'refs/heads/master'
    needs:
      - test
      - build-push-sign
    permissions:
      id-token: write
    runs-on: fasit-deploy
    steps:
      - uses: nais/fasit-deploy@b2c0b6d049b53bef41b321eec406fe66938576fd # ratchet:nais/fasit-deploy@main
        name: Rollout hookd-frontend
        with:
          json: '{"frontend": {"image": {"tag": "${{ needs.build-push-sign.outputs.version }}"}}}'
          feature_name: hookd
